### ISSUE TITLE
Unhandled exception has occurred while executing the request

### ISSUE THREAD

**Issue by dyaeger** [adonisabril/ASPNETCoreMvc_WebAPI_ToDoApp#1]
Following the steps included with this project produced the following error when navigating to `http://localhost:5000/swagger`

![image](https://user-images.githubusercontent.com/21249324/30289964-b6dd84ca-96e2-11e7-80e5-7954e3265c2f.png)

Which produces the following error in the command line:

![image](https://user-images.githubusercontent.com/21249324/30289991-cc9176aa-96e2-11e7-91b7-94445d0788ca.png)

Using:
```
Version 61.0.3163.79 (Official Build) (64-bit)
Widows 10 Pro
.NET Core 2.0.0
```

**Comment by AdonisVillanueva** [comment]
Caused by todo controller changes not pushed. Please try again.
